name: Commit Lint
on:
  pull_request:
  push:
    branches:
    - 'main'
jobs:
  code-checks:
    if: github.actor != 'Gravitik' && github.actor != 'dependabot[bot]'
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Commit Message
        if: github.ref != 'refs/heads/main'
        uses: wagoid/commitlint-github-action@v2
